from io import BytesIO
from xhtml2pdf import pisa
from datetime import datetime
from app.services.dns_lookup import get_dns_records, analyze_dns_security
from app.services.whois_lookup import get_whois_info
from app.services.subdomain_lookup import get_subdomains, analyze_subdomain_security
from app.services.ssl_lookup import analyze_ssl_certificate
from app.services.headers_lookup import get_security_headers, analyze_security_headers
from app.services.email_auth_lookup import check_email_authentication
from app.services.ai_summary import generate_plain_english_summary


def _findings_html(findings: list) -> str:
    color_map = {"critical": "#dc2626", "warning": "#d97706", "info": "#2563eb"}
    items = ""
    for f in findings:
        color = color_map.get(f.severity, "#374151")
        items += f'<li><span style="color:{color}; font-weight:bold;">[{f.severity.upper()}]</span> {f.message}</li>'
    return f"<ul>{items}</ul>" if items else "<p>No findings.</p>"


def generate_full_report(domain: str) -> bytes:
    dns_records = get_dns_records(domain)
    dns_findings = analyze_dns_security(dns_records)

    whois_result = get_whois_info(domain)

    subdomains = get_subdomains(domain)
    subdomain_findings = analyze_subdomain_security(subdomains)

    ssl_result = analyze_ssl_certificate(domain)

    headers = get_security_headers(domain)
    headers_result = analyze_security_headers(headers)

    email_result = check_email_authentication(domain)

    all_findings = (
        dns_findings + whois_result.findings + subdomain_findings +
        ssl_result["findings"] + headers_result["findings"] + email_result["findings"]
    )
    ai_summary = generate_plain_english_summary(domain, all_findings)

    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Helvetica, Arial, sans-serif; margin: 40px; color: #111827; }}
            h1 {{ color: #1e3a8a; border-bottom: 3px solid #1e3a8a; padding-bottom: 10px; }}
            h2 {{ color: #1e40af; margin-top: 30px; border-bottom: 1px solid #d1d5db; padding-bottom: 5px; }}
            .meta {{ color: #6b7280; font-size: 12px; }}
            .summary-box {{ background: #eff6ff; border-left: 4px solid #2563eb; padding: 15px; margin: 15px 0; }}
            ul {{ line-height: 1.8; }}
        </style>
    </head>
    <body>
        <h1>CyberScope Security Report</h1>
        <p class="meta">Domain: <strong>{domain}</strong> | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}</p>

        <h2>Summary</h2>
        <div class="summary-box">{ai_summary}</div>

        <h2>DNS Records & Security</h2>
        {_findings_html(dns_findings)}

        <h2>WHOIS / Domain Age</h2>
        <p>Registrar: {whois_result.registrar or 'Unknown'} | Age: {whois_result.domain_age_days or 'Unknown'} days</p>
        {_findings_html(whois_result.findings)}

        <h2>Subdomains ({len(subdomains)} found)</h2>
        {_findings_html(subdomain_findings)}

        <h2>SSL/TLS Certificate</h2>
        {_findings_html(ssl_result["findings"])}

        <h2>Security Headers (Score: {headers_result["score"]})</h2>
        {_findings_html(headers_result["findings"])}

        <h2>Email Authentication (SPF/DMARC)</h2>
        {_findings_html(email_result["findings"])}

        <p class="meta" style="margin-top:40px;">Generated by CyberScope — an automated OSINT/security recon tool.</p>
    </body>
    </html>
    """

    output = BytesIO()
    pisa.CreatePDF(html_content, dest=output)
    return output.getvalue()